package br.com.gerpro.model;
// Generated 29/04/2009 19:29:49 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma implements java.io.Serializable {

	private CronogramaId id;
	private PropostaItem propostaItem;
	private String nomeItem;
	private Date dataInicial;
	private Date dataFinal;

	public Cronograma() {
	}

	public Cronograma(CronogramaId id, PropostaItem propostaItem,
			String nomeItem) {
		this.id = id;
		this.propostaItem = propostaItem;
		this.nomeItem = nomeItem;
	}

	public Cronograma(CronogramaId id, PropostaItem propostaItem,
			String nomeItem, Date dataInicial, Date dataFinal) {
		this.id = id;
		this.propostaItem = propostaItem;
		this.nomeItem = nomeItem;
		this.dataInicial = dataInicial;
		this.dataFinal = dataFinal;
	}

	public CronogramaId getId() {
		return this.id;
	}

	public void setId(CronogramaId id) {
		this.id = id;
	}

	public PropostaItem getPropostaItem() {
		return this.propostaItem;
	}

	public void setPropostaItem(PropostaItem propostaItem) {
		this.propostaItem = propostaItem;
	}

	public String getNomeItem() {
		return this.nomeItem;
	}

	public void setNomeItem(String nomeItem) {
		this.nomeItem = nomeItem;
	}

	public Date getDataInicial() {
		return this.dataInicial;
	}

	public void setDataInicial(Date dataInicial) {
		this.dataInicial = dataInicial;
	}

	public Date getDataFinal() {
		return this.dataFinal;
	}

	public void setDataFinal(Date dataFinal) {
		this.dataFinal = dataFinal;
	}

}
