package br.com.gerpro.model;
// Generated 29/04/2009 19:29:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * PropostaItem generated by hbm2java
 */
public class PropostaItem implements java.io.Serializable {

	private PropostaItemId id;
	private Item item;
	private Proposta proposta;
	private Status status;
	private String conteudoItem;
	private Set<Cronograma> cronogramas = new HashSet<Cronograma>(0);
	private Set<ListaFuncao> listaFuncaos = new HashSet<ListaFuncao>(0);
	private Set<Correcao> correcaos = new HashSet<Correcao>(0);

	public PropostaItem() {
	}

	public PropostaItem(PropostaItemId id, Item item, Proposta proposta) {
		this.id = id;
		this.item = item;
		this.proposta = proposta;
	}

	public PropostaItem(PropostaItemId id, Item item, Proposta proposta,
			Status status, String conteudoItem, Set<Cronograma> cronogramas,
			Set<ListaFuncao> listaFuncaos, Set<Correcao> correcaos) {
		this.id = id;
		this.item = item;
		this.proposta = proposta;
		this.status = status;
		this.conteudoItem = conteudoItem;
		this.cronogramas = cronogramas;
		this.listaFuncaos = listaFuncaos;
		this.correcaos = correcaos;
	}

	public PropostaItemId getId() {
		return this.id;
	}

	public void setId(PropostaItemId id) {
		this.id = id;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Proposta getProposta() {
		return this.proposta;
	}

	public void setProposta(Proposta proposta) {
		this.proposta = proposta;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getConteudoItem() {
		return this.conteudoItem;
	}

	public void setConteudoItem(String conteudoItem) {
		this.conteudoItem = conteudoItem;
	}

	public Set<Cronograma> getCronogramas() {
		return this.cronogramas;
	}

	public void setCronogramas(Set<Cronograma> cronogramas) {
		this.cronogramas = cronogramas;
	}

	public Set<ListaFuncao> getListaFuncaos() {
		return this.listaFuncaos;
	}

	public void setListaFuncaos(Set<ListaFuncao> listaFuncaos) {
		this.listaFuncaos = listaFuncaos;
	}

	public Set<Correcao> getCorrecaos() {
		return this.correcaos;
	}

	public void setCorrecaos(Set<Correcao> correcaos) {
		this.correcaos = correcaos;
	}

}
