package br.com.gerpro.model;
// Generated 29/04/2009 19:29:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TipoFuncao generated by hbm2java
 */
public class TipoFuncao implements java.io.Serializable {

	private byte id;
	private String nome;
	private char abreviatura;
	private Set<ListaFuncao> listaFuncaos = new HashSet<ListaFuncao>(0);

	public TipoFuncao() {
	}

	public TipoFuncao(byte id, String nome, char abreviatura) {
		this.id = id;
		this.nome = nome;
		this.abreviatura = abreviatura;
	}

	public TipoFuncao(byte id, String nome, char abreviatura,
			Set<ListaFuncao> listaFuncaos) {
		this.id = id;
		this.nome = nome;
		this.abreviatura = abreviatura;
		this.listaFuncaos = listaFuncaos;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public char getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(char abreviatura) {
		this.abreviatura = abreviatura;
	}

	public Set<ListaFuncao> getListaFuncaos() {
		return this.listaFuncaos;
	}

	public void setListaFuncaos(Set<ListaFuncao> listaFuncaos) {
		this.listaFuncaos = listaFuncaos;
	}

}
