package br.com.gerpro.model;
// Generated 10/03/2009 16:46:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Equipe generated by hbm2java
 */
public class Equipe  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set propostas = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Equipe() {
    }

	
    public Equipe(String nome) {
        this.nome = nome;
    }
    public Equipe(String nome, Set propostas, Set usuarios) {
       this.nome = nome;
       this.propostas = propostas;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getPropostas() {
        return this.propostas;
    }
    
    public void setPropostas(Set propostas) {
        this.propostas = propostas;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


