package br.com.gerpro.model;
// Generated 14/04/2009 09:24:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set perguntas = new HashSet(0);
     private Set propostaItems = new HashSet(0);

    public Item() {
    }

	
    public Item(String nome) {
        this.nome = nome;
    }
    public Item(String nome, Set perguntas, Set propostaItems) {
       this.nome = nome;
       this.perguntas = perguntas;
       this.propostaItems = propostaItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getPerguntas() {
        return this.perguntas;
    }
    
    public void setPerguntas(Set perguntas) {
        this.perguntas = perguntas;
    }
    public Set getPropostaItems() {
        return this.propostaItems;
    }
    
    public void setPropostaItems(Set propostaItems) {
        this.propostaItems = propostaItems;
    }




}


