package br.com.gerpro.model;
// Generated 10/03/2009 16:46:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer id;
     private String semestre;
     private Set propostas = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Periodo() {
    }

	
    public Periodo(String semestre) {
        this.semestre = semestre;
    }
    public Periodo(String semestre, Set propostas, Set usuarios) {
       this.semestre = semestre;
       this.propostas = propostas;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public Set getPropostas() {
        return this.propostas;
    }
    
    public void setPropostas(Set propostas) {
        this.propostas = propostas;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


