package br.com.gerpro.model;
// Generated 10/03/2009 16:46:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proposta generated by hbm2java
 */
public class Proposta  implements java.io.Serializable {


     private Integer id;
     private Equipe equipe;
     private Status status;
     private Periodo periodo;
     private String nome;
     private String dataCriacao;
     private String dataSubmissao;
     private Set propostaItems = new HashSet(0);

    public Proposta() {
    }

	
    public Proposta(Equipe equipe, Status status, Periodo periodo, String nome, String dataCriacao, String dataSubmissao) {
        this.equipe = equipe;
        this.status = status;
        this.periodo = periodo;
        this.nome = nome;
        this.dataCriacao = dataCriacao;
        this.dataSubmissao = dataSubmissao;
    }
    public Proposta(Equipe equipe, Status status, Periodo periodo, String nome, String dataCriacao, String dataSubmissao, Set propostaItems) {
       this.equipe = equipe;
       this.status = status;
       this.periodo = periodo;
       this.nome = nome;
       this.dataCriacao = dataCriacao;
       this.dataSubmissao = dataSubmissao;
       this.propostaItems = propostaItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipe getEquipe() {
        return this.equipe;
    }
    
    public void setEquipe(Equipe equipe) {
        this.equipe = equipe;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDataCriacao() {
        return this.dataCriacao;
    }
    
    public void setDataCriacao(String dataCriacao) {
        this.dataCriacao = dataCriacao;
    }
    public String getDataSubmissao() {
        return this.dataSubmissao;
    }
    
    public void setDataSubmissao(String dataSubmissao) {
        this.dataSubmissao = dataSubmissao;
    }
    public Set getPropostaItems() {
        return this.propostaItems;
    }
    
    public void setPropostaItems(Set propostaItems) {
        this.propostaItems = propostaItems;
    }




}


