package br.com.gerpro.model;

// Generated 18/04/2009 12:04:57 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Artefatos implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Set<Cronograma> cronograma = new HashSet<Cronograma>(0);

	public Artefatos() {
	}

	public Artefatos(String nome) {
		this.nome = nome;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Cronograma> getCronograma() {
		return this.cronograma;
	}

	public void setCronograma(Set<Cronograma> cronograma) {
		this.cronograma = cronograma;
	}

}
