package br.com.gerpro.model;

// Generated 31/05/2009 15:44:42 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Correcao generated by hbm2java
 */
public class Correcao implements java.io.Serializable {

	private CorrecaoId id;
	private PropostaItem propostaItem;
	private Status status;
	private Pergunta pergunta;
	private Resposta resposta;
	private Usuario usuario;
	private String observacao;
	private Date dataCorrecao;

	public Correcao() {
	}

	public Correcao(CorrecaoId id, PropostaItem propostaItem, Status status,
			Pergunta pergunta, Usuario usuario) {
		this.id = id;
		this.propostaItem = propostaItem;
		this.status = status;
		this.pergunta = pergunta;
		this.usuario = usuario;
	}

	public Correcao(CorrecaoId id, PropostaItem propostaItem, Status status,
			Pergunta pergunta, Resposta resposta, Usuario usuario,
			String observacao, Date dataCorrecao) {
		this.id = id;
		this.propostaItem = propostaItem;
		this.status = status;
		this.pergunta = pergunta;
		this.resposta = resposta;
		this.usuario = usuario;
		this.observacao = observacao;
		this.dataCorrecao = dataCorrecao;
	}

	public CorrecaoId getId() {
		return this.id;
	}

	public void setId(CorrecaoId id) {
		this.id = id;
	}

	public PropostaItem getPropostaItem() {
		return this.propostaItem;
	}

	public void setPropostaItem(PropostaItem propostaItem) {
		this.propostaItem = propostaItem;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Pergunta getPergunta() {
		return this.pergunta;
	}

	public void setPergunta(Pergunta pergunta) {
		this.pergunta = pergunta;
	}

	public Resposta getResposta() {
		return this.resposta;
	}

	public void setResposta(Resposta resposta) {
		this.resposta = resposta;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public Date getDataCorrecao() {
		return this.dataCorrecao;
	}

	public void setDataCorrecao(Date dataCorrecao) {
		this.dataCorrecao = dataCorrecao;
	}

}
