package br.com.gerpro.model;

// Generated 31/05/2009 15:44:42 by Hibernate Tools 3.2.2.GA

/**
 * CorrecaoId generated by hbm2java
 */
public class CorrecaoId implements java.io.Serializable {

	private int idProposta;
	private int idItem;
	private String matriculaProfessor;
	private int idPergunta;

	public CorrecaoId() {
	}

	public CorrecaoId(int idProposta, int idItem, String matriculaProfessor,
			int idPergunta) {
		this.idProposta = idProposta;
		this.idItem = idItem;
		this.matriculaProfessor = matriculaProfessor;
		this.idPergunta = idPergunta;
	}

	public int getIdProposta() {
		return this.idProposta;
	}

	public void setIdProposta(int idProposta) {
		this.idProposta = idProposta;
	}

	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public String getMatriculaProfessor() {
		return this.matriculaProfessor;
	}

	public void setMatriculaProfessor(String matriculaProfessor) {
		this.matriculaProfessor = matriculaProfessor;
	}

	public int getIdPergunta() {
		return this.idPergunta;
	}

	public void setIdPergunta(int idPergunta) {
		this.idPergunta = idPergunta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorrecaoId))
			return false;
		CorrecaoId castOther = (CorrecaoId) other;

		return (this.getIdProposta() == castOther.getIdProposta())
				&& (this.getIdItem() == castOther.getIdItem())
				&& ((this.getMatriculaProfessor() == castOther
						.getMatriculaProfessor()) || (this
						.getMatriculaProfessor() != null
						&& castOther.getMatriculaProfessor() != null && this
						.getMatriculaProfessor().equals(
								castOther.getMatriculaProfessor())))
				&& (this.getIdPergunta() == castOther.getIdPergunta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProposta();
		result = 37 * result + this.getIdItem();
		result = 37
				* result
				+ (getMatriculaProfessor() == null ? 0 : this
						.getMatriculaProfessor().hashCode());
		result = 37 * result + this.getIdPergunta();
		return result;
	}

}
