package br.com.gerpro.model;

// Generated 31/05/2009 15:44:42 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma implements java.io.Serializable {

	private CronogramaId id;
	private PropostaItem propostaItem;
	private Artefatos artefatos;
	private Date dataInicial;
	private Date dataFinal;

	public Cronograma() {
	}

	public Cronograma(CronogramaId id, PropostaItem propostaItem,
			Artefatos artefatos) {
		this.id = id;
		this.propostaItem = propostaItem;
		this.artefatos = artefatos;
	}

	public Cronograma(CronogramaId id, PropostaItem propostaItem,
			Artefatos artefatos, Date dataInicial, Date dataFinal) {
		this.id = id;
		this.propostaItem = propostaItem;
		this.artefatos = artefatos;
		this.dataInicial = dataInicial;
		this.dataFinal = dataFinal;
	}

	public CronogramaId getId() {
		return this.id;
	}

	public void setId(CronogramaId id) {
		this.id = id;
	}

	public PropostaItem getPropostaItem() {
		return this.propostaItem;
	}

	public void setPropostaItem(PropostaItem propostaItem) {
		this.propostaItem = propostaItem;
	}

	public Artefatos getArtefatos() {
		return this.artefatos;
	}

	public void setArtefatos(Artefatos artefatos) {
		this.artefatos = artefatos;
	}

	public Date getDataInicial() {
		return this.dataInicial;
	}

	public void setDataInicial(Date dataInicial) {
		this.dataInicial = dataInicial;
	}

	public Date getDataFinal() {
		return this.dataFinal;
	}

	public void setDataFinal(Date dataFinal) {
		this.dataFinal = dataFinal;
	}

}
