package Model;

// Generated 18/04/2009 12:04:57 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Equipe generated by hbm2java
 */
public class Equipe implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Set<Proposta> propostas = new HashSet<Proposta>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Equipe() {
	}

	public Equipe(String nome) {
		this.nome = nome;
	}

	public Equipe(String nome, Set<Proposta> propostas, Set<Usuario> usuarios) {
		this.nome = nome;
		this.propostas = propostas;
		this.usuarios = usuarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Proposta> getPropostas() {
		return this.propostas;
	}

	public void setPropostas(Set<Proposta> propostas) {
		this.propostas = propostas;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
