package Model;

// Generated 18/04/2009 12:04:57 by Hibernate Tools 3.2.2.GA

/**
 * ListaFuncaoId generated by hbm2java
 */
public class ListaFuncaoId implements java.io.Serializable {

	private int idProposta;
	private int numeroSequencia;
	private int idItem;

	public ListaFuncaoId() {
	}

	public ListaFuncaoId(int idProposta, int numeroSequencia, int idItem) {
		this.idProposta = idProposta;
		this.numeroSequencia = numeroSequencia;
		this.idItem = idItem;
	}

	public int getIdProposta() {
		return this.idProposta;
	}

	public void setIdProposta(int idProposta) {
		this.idProposta = idProposta;
	}

	public int getNumeroSequencia() {
		return this.numeroSequencia;
	}

	public void setNumeroSequencia(int numeroSequencia) {
		this.numeroSequencia = numeroSequencia;
	}

	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListaFuncaoId))
			return false;
		ListaFuncaoId castOther = (ListaFuncaoId) other;

		return (this.getIdProposta() == castOther.getIdProposta())
				&& (this.getNumeroSequencia() == castOther.getNumeroSequencia())
				&& (this.getIdItem() == castOther.getIdItem());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProposta();
		result = 37 * result + this.getNumeroSequencia();
		result = 37 * result + this.getIdItem();
		return result;
	}

}
