package br.com.gerpro.model;

// Generated 18/04/2009 12:04:57 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Pergunta generated by hbm2java
 */
public class Pergunta implements java.io.Serializable {

	private Integer id;
	private Item item;
	private String descricao;
	private Set<Correcao> correcaos = new HashSet<Correcao>(0);

	public Pergunta() {
	}

	public Pergunta(Item item, String descricao, Set<Correcao> correcaos) {
		this.item = item;
		this.descricao = descricao;
		this.correcaos = correcaos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Set<Correcao> getCorrecaos() {
		return this.correcaos;
	}

	public void setCorrecaos(Set<Correcao> correcaos) {
		this.correcaos = correcaos;
	}

}
