package Model;

// Generated 18/04/2009 12:04:57 by Hibernate Tools 3.2.2.GA

/**
 * Periodo generated by hbm2java
 */
public class Periodo implements java.io.Serializable {

	private Integer id;
	private String semestre;

	public Periodo() {
	}

	public Periodo(String semestre) {
		this.semestre = semestre;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

}
